server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: file_pipeline
    static_configs:
      # 目标 1: 转发服务
      - targets: ['localhost']
        labels:
          job: file_system
          service: forward_svc
          __path__: /var/log/app/service-forward/*.log
      
      # 目标 2: 处理服务
      - targets: ['localhost']
        labels:
          job: file_system
          service: process_svc
          __path__: /var/log/app/service-process/*.log
